### PR TITLE
Eva Data and Files from Yolanda

### PR DESCRIPTION
**Pull request by YolandaMING**

### CODE REVIEW

**Comment by YolandaMING** [comment]
Add some comments in the readme

**Comment by manishvenu** [comment]
Hey y'all, should we put the evaporation data in the main/master branch and the code in a different branch or folder? Because the code is part of one method of which we might have more than one evaporation calculation method but the pan data is universal?

**Comment by YolandaMING** [comment]
I put the data in the data folder and the code in the script folder but if we want to use branches I can move them there!

**Comment by manishvenu** [comment]
I'm not super sure how we should organize it. The main thing I was thinking about was that the next time we have a different method, having all the code scripts in one folder might be messy. 

Having each method in one branch might be best (i.e. place data on the master branch, create a branch off of master - so that both the branch and the master has the evaporation data, and put code specific to the assumption in the branch). Even more simply, we could just create specific folders for each method, but that might also be messy!

**Comment by YolandaMING** [comment]
Oh I totally agree with the branch idea - it should be more organized by throwing everything in the main branch! I will wait for Anne's reply for the confirmation and then create a branch for my code!

**Comment by annefetrow** [comment]
looking great so far

**Pull request merged**
